/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export type RecorderBiographies = {
  language: string | Language;
  biography?: string;
  id?: string;
}[];

export interface Config {
  collections: {
    Users: User;
    Languages: Language;
    Recorders: Recorder;
    Images: Image;
  };
  globals: {};
}
export interface User {
  id: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Language {
  id: string;
  name: string;
}
export interface Recorder {
  id: string;
  username: string;
  anonymize: boolean;
  languages?: string[] | Language[];
  biographies?: RecorderBiographies;
}
export interface Image {
  id: string;
  alt?: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
